### ISSUE TITLE
Change style

### ISSUE THREAD

**Issue by PierreMarchand20** [zimfw/autosuggestions#1] opened 2018-10-09 12:41 UTC
Disclaimer: I have a really hard time to understand how everything works with zsh and I come from prezto.

I would like to change the style of autosuggestion. In zpreztorc, there is a line to do it
`zstyle ':prezto:module:autosuggestions:color' found 'fg=241'`

But with zim, I do not how to use the command 'ztyle' with autosuggestion. I write zstyle in command line and search for autocompletion with tab, it only finds completion, vcs_info and zftp. Is there something to configure in the autosuggestion package to be able to change it this way ?

**Comment by PierreMarchand20** [comment] 2018-10-09 13:04
Actually, looking at git-info, I should be able to use it for this module also but it does not work when I try to change the verbose value.

**Comment by ericbn** [comment] 2018-10-15 01:50
@PierreMarchand20, add this to your `~/.zimrc` file:
```
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'
```
zim uses the zsh-autosuggestions module, and you can configure it as described here: https://github.com/zsh-users/zsh-autosuggestions#configuration

**Comment by ericbn** [comment] 2018-10-15 01:51
Closing this as duplicate of https://github.com/zimfw/zimfw/issues/301

**Closed by ericbn** 2018-10-15 01:51 UTC
